# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the podman-notebook directory and image
# Set the workflow name
name: JHub Podman Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/podman-notebook/ path
on:
  push:
    paths:
      - podman-notebook/**

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  podman-build-podman-notebook:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: arc-runner-set
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Container Image
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build Podman image
        run: |
          podman build -f images/podman-notebook/Containerfile -t hub.k8s.ucar.edu/cislcloudpilot/ccpp-jhub-podman:${{ steps.date.outputs.date }} images/podman-notebook/. --no-cache --format=docker
      - name: Create pull request to merge dev in to main
        run: gh pr view ${{ env.BRANCH_NAME }} && gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create -B main -H ${{ env.BRANCH_NAME }}  --title 'Test build successful. Merge Podman notebook update from dev into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}